version: '3'

services:
  docker_backup_pro_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "1146:1238"
    command: "node index"
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/backup_pro  # MongoDB connection string
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
